### ISSUE TITLE
There is a problem with the display on macos

### ISSUE THREAD

**Issue by Richard-Tang** [andrewauclair/ModernDocking#65] opened 2023-06-18 12:12 UTC
The same jar package code, when displayed on MACOS, there will be a visual bug.

When I drag and drop on MACOS, it looks like this: the feature works, but it doesn't appear as complete as it does on Windows.

```bash
java 11.0.16.1 2022-08-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.16.1+1-LTS-1)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.16.1+1-LTS-1, mixed mode)
```

<img width="921" alt="image" src="https://github.com/andrewauclair/ModernDocking/assets/30547741/93e81c99-dbc5-41c6-a16c-a1511b5f20df">

It is displayed normally on windows

```bash
java 11.0.12 2021-07-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)
```

![image](https://github.com/andrewauclair/ModernDocking/assets/30547741/2bff8425-3d7b-4cd1-b29b-a619a3df8fb7)

**Comment by andrewauclair** [comment] 2023-06-18 13:17
Unfortunately, I don't own a Mac and don't have access to one. I did recently rework how the sizes are chosen for the overlay and floating frame. Maybe that will fix the issue. I'm going to be publishing a 0.6.0 soon (possibly today).

**Comment by Richard-Tang** [comment] 2023-06-18 15:58
> Unfortunately, I don't own a Mac and don't have access to one. I did recently rework how the sizes are chosen for the overlay and floating frame. Maybe that will fix the issue. I'm going to be publishing a 0.6.0 soon (possibly today).

The new 0.0.6 code will still have this problem

**Comment by tlf30** [comment] 2023-07-01 19:21
You may try jdk 19. I have seen a lot of issues in jdk 11 & 17 with swing for some reason, but jdk 19 seems to fix all but one that I have come across

**Comment by tlf30** [comment] 2023-07-09 03:02
I'm now seeing a similar on JDK 17 with 4k displays, also the drop locations are not correct. I think this may be a java issue. I will test with JDK 19 on the same displays and see how it behaves.

**Comment by andrewauclair** [comment] 2023-07-09 04:36
I do recall there being some dpi issues with an older version. I will see if I can reproduce the issue with some older versions and display settings.

**Comment by tlf30** [comment] 2023-07-14 21:41
So, on windows, with JDK 20, with two different screens, there are strange issues with rendering the drop points.
Tested Screens
3840x2160
5120x1440

The drop overlay renders in a strange blue color, and does not even necessary overlap with the entire app. Instead it is in the upper left of the app. The actual look of the overlay looks nothing like what it should, and instead is just a rectangle or two that is light blue. But on my super wide monitor, it correctly renders the overlap with the correct blue shading, but it does not size correctly. 
![example2](https://github.com/andrewauclair/ModernDocking/assets/10089434/c17b4b96-424f-4f9f-9c6a-ba73085328ad)
![example1](https://github.com/andrewauclair/ModernDocking/assets/10089434/e5f9a6d7-de8c-4c20-a927-94b56e168f6b)

**Comment by andrewauclair** [comment] 2023-07-14 21:57
Wow, that is very strange. I'll see if I can get it to do that. So far, I have tried it out on Java 9 with 150% scaling and I see an issue there with the position when floating a dockable. The overlay has looked ok though.

**Comment by andrewauclair** [comment] 2023-07-14 22:02
> So, on windows, with JDK 20, with two different screens, there are strange issues with rendering the drop points. Tested Screens 3840x2160 5120x1440
> 
> The drop overlay renders in a strange blue color, and does not even necessary overlap with the entire app. Instead it is in the upper left of the app. The actual look of the overlay looks nothing like what it should, and instead is just a rectangle or two that is light blue. But on my super wide monitor, it correctly renders the overlap with the correct blue shading, but it does not size correctly. ![example2](https://user-images.githubusercontent.com/10089434/253687464-c17b4b96-424f-4f9f-9c6a-ba73085328ad.PNG) ![example1](https://user-images.githubusercontent.com/10089434/253687471-e5f9a6d7-de8c-4c20-a927-94b56e168f6b.PNG)

I wonder if it is confused about which window your mouse is over. At least in that first image, the highlight looks to be the perfect size to fit in the top half of the other frame.

**Comment by andrewauclair** [comment] 2023-07-14 22:06
Wow, no. That's the dockable that's floating, not another frame. Forget what I said (It has been too long of a day).

**Comment by andrewauclair** [comment] 2023-07-15 00:06
```java
for (GraphicsDevice screenDevice : env.getScreenDevices()) {
    System.out.println("scale for: " + screenDevice.getIDstring() + ": " + screenDevice.getDefaultConfiguration().getDefaultTransform().getScaleX() + ", " + screenDevice.getDefaultConfiguration().getDefaultTransform().getScaleY());
}
```
@tlf30 Hey, could you tell me what this code outputs on your setup?

I believe most of this boils down to me not using the scaling properly. Essentially that makes almost all the positioning wrong. Funny enough, the center docking handles are the only things I use the scale for. That's why they appear huge in the original screenshot in this issue.

I did more testing on 150% and the drag position was way off. I scaled the mouse position using the above code and the position was fixed. However, that only works on the 150% monitor. I need to figure out how you tell which monitor you're on and using the scaling for that. This might take some time.

**Comment by tlf30** [comment] 2023-07-15 00:24
Absolutely, here is the output
```
scale for: \Display0: 1.25, 1.25
scale for: \Display1: 2.0, 2.0
```

**Comment by Richard-Tang** [comment] 2023-07-15 12:34
> I'm now seeing a similar on JDK 17 with 4k displays, also the drop locations are not correct. I think this may be a java issue. I will test with JDK 19 on the same displays and see how it behaves.

I tested it on macos jdk19 and found the same problem.

![image](https://github.com/andrewauclair/ModernDocking/assets/30547741/59a13b41-72de-48ce-9797-615a839fd4aa)

When I try to drag, the component behind the background temporarily disappears.

![image](https://github.com/andrewauclair/ModernDocking/assets/30547741/707c6dfd-e040-458f-8e6c-8b51e8755829)

**Comment by andrewauclair** [comment] 2023-07-15 13:31
Hard to see, but it looks like the DockingUtilsFrame where the handles are drawn isn't being hidden. This frame is set as undecorated (this part looks to be working) and the background is set to `new Color(0, 0, 0, 0)` to make it transparent. This must not work properly on macOS. I'll see if the internet has any suggestions.

**Comment by andrewauclair** [comment] 2023-07-15 14:13
@Richard-Tang It turns out that transparency works a little different on macOS. I have committed a change to use the client property "Window.alpha". Apparently you have to set that to 0.0f instead of using `setBackground(new Color(0, 0, 0, 0));`

If you're able to try it out, that would be great. I am still investigating the other scaling issues.

**Comment by Richard-Tang** [comment] 2023-07-15 14:37
> @Richard-Tang It turns out that transparency works a little different on macOS. I have committed a change to use the client property "Window.alpha". Apparently you have to set that to 0.0f instead of using `setBackground(new Color(0, 0, 0, 0));`
> 
> If you're able to try it out, that would be great. I am still investigating the other scaling issues.

This time it is indeed transparent, but without ModernDocking layout display!

![image](https://github.com/andrewauclair/ModernDocking/assets/30547741/ee1f6f00-f8e2-483a-8561-f6e676739993)

The original layout component is no longer displayed.

![image](https://github.com/andrewauclair/ModernDocking/assets/30547741/7dc7893a-0db1-465f-bb10-576d48185b0a)

**Comment by andrewauclair** [comment] 2023-07-16 00:45
@Richard-Tang Interesting. We're learning something! I've been doing some research about translucency/transparency in Java Swing. I've added a new test class to basic-demo. Could you run [`TranslucentTest.java` ](https://github.com/andrewauclair/ModernDocking/blob/67f6a91792f425a69c81d38d49ed4e1c4de408bd/demo/src/tests/TranslucentTest.java) and comment here with what the output is.

For example, when I run it on my Windows 11 machine it outputs the following.
```
Is uniform translucency supported: true
Is per-pixel translucency supported: true
Is shaped window supported: true
```

**Comment by andrewauclair** [comment] 2023-07-16 00:46
I suspect that macOS doesn't support the per-pixel translucency and that's what we're seeing here. Either way, this looks like something I need to consider and have a backup solution for when the transparency tricks won't work.

**Comment by Richard-Tang** [comment] 2023-07-16 11:56
> For example, when I run it on my Windows 11 machine it outputs the following.

```log
> Task :TranslucentTest.main()
Is uniform translucency supported: true
Is per-pixel translucency supported: true
Is shaped window supported: true
```

**Comment by andrewauclair** [comment] 2023-07-16 17:10
Well, there goes that theory. I guess macOS supports it but it doesn't work the same.

**Comment by andrewauclair** [comment] 2023-07-16 20:57
@Richard-Tang Undid the previous change and set the background color of the content pane to be transparent. I have my fingers crossed that does something, if you wouldn't mind trying.

**Comment by andrewauclair** [comment] 2023-07-17 11:36
I made another change based on what was discovered in Issue #68 that might be related to this issue as well. I am publishing a 0.6.1 right now which should be available on maven central later this morning.

**Comment by Richard-Tang** [comment] 2023-07-23 12:07
#68 This solves the translucent issue on MacOS

But in the latest code, `instanceof JComponen`，Actually `getContentPane()` is a JPanel

```java
try {
	if (getContentPane() instanceof JComponent) {
		((JComponent) getContentPane()).setOpaque(false);
	}
}
catch (IllegalComponentStateException e) {
	// TODO we need to handle platforms that don't support translucent display
	// this exception indicates that the platform doesn't support changing the opacity
}
```

<img width="1345" alt="image" src="https://github.com/andrewauclair/ModernDocking/assets/30547741/2ef16c6f-8e4b-4dc8-a219-1e0602a91254">

It currently works on MacOS `((JComponent) getContentPane()).setOpaque(false);`

![image](https://github.com/andrewauclair/ModernDocking/assets/30547741/29ac4937-1c9a-454e-94f9-3277eaab1fe0)

![image](https://github.com/andrewauclair/ModernDocking/assets/30547741/5a53bc42-8a4e-4eb1-b113-e352284e59d1)

**Comment by andrewauclair** [comment] 2023-07-23 12:47
A `JPanel` is a `JComponent`. `getContentPane()` returns a `JComponent` so I didn't want to make assumptions. 

Looks good. Something still seems a little off with the handles, but at least they're rendering with transparency.

**Comment by andrewauclair** [comment] 2023-07-30 01:05
@Richard-Tang Could you try out the latest? I wrote issue #72 related to this issue. Turns out, the special RepaintManager that I use to check for EDT violations breaks the transparency on Linux and I suspect the same happens on MacOS. I modified the demo to have this off by default.

This would also be a problem for apps derived from my example code if they kept the `FailOnThreadViolationRepaintManager.install();` line.

**Comment by Richard-Tang** [comment] 2023-07-30 12:39
`--laf=light`

`--laf=light --enable-edt-violation-detector=true`

![image](https://github.com/andrewauclair/ModernDocking/assets/30547741/5d2a3f8c-e4b3-4830-9dd9-4053efb5a6f8)

`--laf=dark --enable-edt-violation-detector=true`

![image](https://github.com/andrewauclair/ModernDocking/assets/30547741/c74bfc1c-4d8e-4484-ad25-e739d5f38bb7)

Now the test situation is that the add `--enable-edt-violation-detector`, Will have display problems.

**Comment by andrewauclair** [comment] 2023-07-30 12:43
I'm a little confused. Is there a missing screenshot there with the detector off?

**Comment by Richard-Tang** [comment] 2023-07-30 12:47
`--laf=dark --enable-edt-violation-detector=false`

`--laf=light --enable-edt-violation-detector=false`

![image](https://github.com/andrewauclair/ModernDocking/assets/30547741/b8b604b1-cd03-4bda-a4b5-72f3c906ef60)

![image](https://github.com/andrewauclair/ModernDocking/assets/30547741/ba7b02ec-f7df-4ed6-ac1f-c76cf42fff67)

**Comment by andrewauclair** [comment] 2023-07-30 12:50
Damn :( I had taken out a few of the other changes I made. Maybe that was a bad idea.

**Comment by andrewauclair** [comment] 2023-08-07 22:20
@Richard-Tang Getting back to this again. What does it display with `--laf=dark --enable-edt-violation-detector=false`?

I noticed that before when it was working you were running my `Example.java` and now when it wasn't working again you were using the basic demo `MainFrame.java`. I wonder if it's some issue with those look and feels on MacOS.

**Comment by andrewauclair** [comment] 2023-08-08 13:09
I came across this FlatLaf MacOS transparency issue last night (https://github.com/JFormDesigner/FlatLaf/issues/705) that has a very similar issue. I will try the suggested workaround for 0.7.2.

**Comment by andrewauclair** [comment] 2023-08-09 12:30
0.7.2 has the workaround in it now.

**Comment by andrewauclair** [comment] 2023-10-01 20:05
Closing. I believe this has been resolved.

**Closed by andrewauclair** 2023-10-01 20:05 UTC
Labels: bug
